
name: T.H.E.S.E. MistakeBot (Apply Labels)

on:
  issue_comment:
    types:
      - edited

jobs:
  mistakebot_apply_label:
    if: contains( github.event.issue.labels.*.name, 'to-err-is-human')
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.comment.body }}
          regex: \- \[x\] (A[SL]\d+)
          flags: gm
      # - name: add label
      #   uses: actions-ecosystem/action-add-labels@v1
      #   with:
      #     labels: bug
      - uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            TESTING REGEX: ${{ steps.regex-match.outputs.group1 }}






