
name: T.H.E.S.E. MistakeBot

on:
  issues:
    types:
      - labeled

jobs:
  mistakebot:
    if: contains( github.event.issue.labels.*.name, 'to-err-is-human')
    runs-on: ubuntu-latest
    container:
      image: andymeneely/squib

    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
      - name: Query for other mistake issues
        uses: octokit/graphql-action@v2.x
        id: count-err-issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
           {
              repository(owner: "VulnerabilityHistoryProject", name: "vulnerability-history") {
                issues(labels: "to-err-is-human", first: 100) {
                  edges {
                    node {
                      id
                      number
                      title
                    }
                  }
                }
              }
            }
      - name: Run Squib
      # docker run --rm -v "%cd%":/usr/src/app andymeneely/squib ruby hello.rb
        run: |
          ruby hello.rb
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: mistakes
          message: |
            :microscope: Hello, there! I'm MistakeBot.

            This is issue ${{ github.event.issue.number }} right?

            All "err" issues:

            ${{ fromJSON(steps.count-err-issues.outputs.data).repository.issues.edges[0].node.title}}

            # Slips

            - [ ] AS1 **Typos & Misspellings**: Typos and misspellings may occur in code comments, or when typing the name of a variable, function, or class. AL1 Working With Outdated Source Code: Forgetting to git-pull (or equivalent in other version control systems), or using an outdated version of a library.

            # Lapses
            - [ ] AL1 **Working With Outdated Source Code**: Forgetting to git-pull (or equivalent in other version control systems), or using an outdated version of a library.
            - [ ] AL2 Forgetting an Import Statement: Forgetting to import a necessary library, class, variable, or function, or
            forgetting to include arguments in a function call.







